CREATE  DATABASE saledb OWNER postgres TABLESPACE default;
CREATE TABLE Providers (
    Id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    NameProvider varchar(40) NOT NULL,
    Email varchar(40) NOT NULL,
    phone bigint NOT NULL,
    Nit varchar(20) NOT NULL
);

CREATE TABLE Users (
     Id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     NameUser   varchar(40) NOT NULL CHECK (NameUser <> ''),
     Email   varchar(40) NOT NULL CHECK (Email <> ''),
     Password   varchar(40) NOT NULL CHECK (Password <> '')
);

CREATE TABLE Products (
    Id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    NameProduct varchar(40) NOT NULL,
    CreationDate date NOT NULL,
    Price decimal(18,2) NOT NULL,
    ProviderId integer REFERENCES Providers(Id),
    Code integer
);

CREATE TABLE Sales (
     Id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     Cantity   integer NOT NULL,
     DateSale date NOT NULL,
     TaxValue integer,
     TotalAmount decimal(18,2) NOT null,
     ProductId integer REFERENCES Products(Id),
     UserId integer REFERENCES Users(Id)
);
